spring.application.name=E-Insurance

# ===============================
# SERVER
# ===============================

server.port=8080


# ===============================
# POSTGRESQL DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/einsurance
spring.datasource.username=postgres
spring.datasource.password=ABCD
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# JWT
# ===============================

jwt.secret=my-super-secret-key-for-einsurance-application-2026
jwt.expiration=3600000